### ISSUE TITLE
Bug: date for Add statement page is in English format

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#137]
When I added a new statement, I encountered the following error message:

![bug_English_date_adaugă_o_afirmație_Dignitas](https://user-images.githubusercontent.com/1265882/86249691-4be69280-bbb8-11ea-8370-4d7fc9a2a67a.png)

I wrote the statement date in the Romanian format (day/month/year), but the interface required the date in the English format (month/day/year).

**Comment by CatalinFrancu** [comment]
Switched to [bootstrap-datepicker](https://uxsolutions.github.io/bootstrap-datepicker), which now pops up a calendar in the correct locale.

The field format is now `YYYY-MM-DD` regardless of the locale. It would be nicer to display a human-readable value such as "24 aprilie 2020" or "April 20, 2020". However, that takes some work because the value needs to be converted to numeric before submitting the form. Please reopen if this is important.
