### ISSUE TITLE
Make verdicts visible in statement boxes

### ISSUE THREAD

**Issue by CatalinFrancu** [TeamDignitas/dignitas#150]
Should verdicts be visible in statement boxes?

* On the home page carousel.
* On [author pages](https://dignitas.ro/autor/10).
* Should verdict colors also be included?

**Comment by sandriu** [comment]
For home page, the least invasive method to display the verdict for each statement would be:
1) to set the border colour of the statement box equal to the verdict colour (visible anytime);
2) on hover on a statement box, the statement box area to transition into an area with different opacity and the verdict's background colour, plus a central label that displays the full text of the verdict (eg. 'În general adevărat').

On author pages, the border colour could be used to mark the statement's verdict.

A legend for verdict colours should be included on home page, above the list of all recent statements, since this is a new platform with a new UI that users must learn to use it from scratch.

**Comment by CatalinFrancu** [comment]
Currently it looks like this:

![Screenshot_2020-10-14_11-40-52](https://user-images.githubusercontent.com/1180392/95965057-2f423380-0e12-11eb-81f9-e3d8e56931aa.png)

The trouble is that we want _both_ the statement and the author to be clickable, and fading the box would interfere with that. So for now I left the opacity alone and anchored the verdict to the bottom-left.

**Comment by CatalinFrancu** [comment]
Also see the [help page](https://dignitas.ro/ajutor/verdicte) for the color legend.

**Comment by sandriu** [comment]
> Also see the [help page](https://dignitas.ro/ajutor/verdicte) for the color legend.

Color legend from Help Page looks good. I think we can skip the color legend on home page, at least for now.

**Comment by sandriu** [comment]
An idea for including the color legend on home page would be to display the colours inside the verdict list, similar to this example from the internet:
![select_with_flags](https://user-images.githubusercontent.com/1265882/95991032-efd90e80-0e34-11eb-9bfb-085f6954244d.jpg)

**Comment by CatalinFrancu** [comment]
I _think_ this can be closed. Please reopen if I forgot anything.
