### ISSUE TITLE
Improve page 'Posts from new users'

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#192]
This page is hard to use because the UI doesn't inform the user well which sections are read-only and which are actionable:

> ![Mesaje-de-la-utilizatori-noi-Dignitas](https://user-images.githubusercontent.com/1265882/101189407-af8d5400-365f-11eb-8d21-4097749ae979.png)

**Comment by sandriu** [comment]
Questions for brainstorming with @CatalinFrancu:
1) do we need the comment button and the ellipsis menu within a new message (to be analysed)? If not, then we could hide it on this page.
2) what's the difference between the textfield '_detalii (opționale)_' and the comment option within a message?
3) do we need the verdict label for a new message?
4) what's the default scenario for a moderator: is he/she automatically subscribed to all statements? Or is this page (New Messages) the only place to trace active statements (i.e., statements on which people are commenting)?
5) do we need the whole verdict card within the statement quote (author, date, picture and verdict) or just the verdict? Note that inside the statement quote the author & date are duplicates.
6) do we need the 'urmărește' and 'arată versiunile' buttons within the statement quote?

**Comment by CatalinFrancu** [comment]
As a general rule, this interface serves not only for reviewing new messages, but also other types of messages:

* flagged messages;
* late answers to old questions;
*  suggested edits.

These probably require slightly different layouts and actions, so let's tweak them on a case-by-case basis!

> 1. do we need the comment button and the ellipsis menu within a new message (that has to be analysed)? If not, then we could hide it on this page.

> 6. do we need the _'urmărește_' and '_arată versiunile_' buttons within the statement quote? If not, then we could hide them to simplify the page.

* ⚑ Flagging is generally useful. If the message is bad (spam, offensive etc.), it is best to say why rather than just to simply vote to delete it. This is done via flagging.
* 🗩 Commenting is generally useful. Adding a canned response (e.g. _please dont' post an answer just to say Thank you_) helps the user understand why their answer is being removed.
* ⧗ The history link is useless for new objects, but could be useful for other reviews (flagged items).
* ✎ The edit link can be removed if you want. There is an edit button on the top bar.
* Other buttons are clearly misplaced here, for example [Add a statement] when reviewing an author. I will evaluate them individually.

> 2. what's the difference between the textfield '_detalii (opționale)_' and the comment option within a message?

The details (short comments from the reviewer) are visible in the review report (the alert-like message that becomes visible once the review is complete). Comments are just regular comments (like commenting from the statement page).

I thought it was a good idea for reviewers to be able to justify their decision separately from the flow of information on the page. But I don't feel strongly either way.

> 3. do we need the verdict label for a new message?

Does it hurt to include it? For new statements it will probably be "none", but for flagged items and suggested changes it might be relevant.

> 4. what's the default scenario for a moderator: is he/she automatically subscribed to all statements? Or is this page (New Messages) the only place to trace active statements (i.e., statements on which people are commenting)?

Moderators currently get notified of all reviews. But if a high-reputation user adds a statement and another high-reputation user posts an answer, these events will not trigger reviews. It would be good to have a "recent events" page, but that's a separate topic.

> 5. do we need the whole verdict card within the statement quote (author, date, picture and verdict) or just the verdict? Note that inside the statement quote the author & date are duplicates.

The only other element in that box is the author's picture, which presumably was already reviewed elsewhere. So we can skip the box.

**Comment by sandriu** [comment]
Remaining TODOs on this page:
- [ ] rounded corner on all cards
- [ ] stacked fields for quoted statement on mobile (entity, date, sources):
![20210222_165358](https://user-images.githubusercontent.com/1265882/108725826-74e4da80-752f-11eb-9f86-21e5d985090e.jpg)


- [ ] better display of comment area inside the message, on mobile:
![20210222_165442](https://user-images.githubusercontent.com/1265882/108725866-7ca47f00-752f-11eb-8541-8de33f2cec7b.jpg)

![message-comment-icon-placed-weird](https://user-images.githubusercontent.com/1265882/108724435-fc314e80-752d-11eb-850f-90b37cba16c3.jpg)

- [ ] hide Votes table if empty:
![message-votes-table-empty-still-displayed](https://user-images.githubusercontent.com/1265882/108724537-19661d00-752e-11eb-9609-87db8fc6122f.jpg)

**Comment by sandriu** [comment]
I fixed the remaining issue from the 22 February TODO list and tested on mobile.
