### ISSUE TITLE
Default order for home page statements

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#227]
We want to avoid the scenario in which the home page is mainly occupied by statements of the same entity, for example after we introduced the electoral program of a winning candidate:

![home-page-mainly-occupied-by-same-entity](https://user-images.githubusercontent.com/1265882/108221111-1b9c3600-7140-11eb-9cee-4704610db0ed.png)

To brainstorm the following options:

- [ ] we display only 1 statement from each entity on home page, eg. the latest one or the analysed one; all other statements of that entity can be accessed from the entity profile page;
- [x]  we display the analysed statements first, on home page; this way, electoral promises (which cannot be verified for now) will not occupy the home page.
- [ ]  TBD.

**Comment by CatalinFrancu** [comment]
Another thought: Statements with recent verdicts should also show at the top. Receiving a verdict is a notable event in a statement's life cycle. This is especially true for promises, which are uninteresting at first and which can lie dormant for years.

Formally, when ranking a statement, we would use the verdict timestamp if available, otherwise the (usual) creation date.

**Comment by sandriu** [comment]
> Statements with recent verdicts should also show at the top.
> Formally, when ranking a statement, we would use the verdict timestamp if available, otherwise the (usual) creation date.

Let's implement this type of order.
