### ISSUE TITLE
Automatically create a permanent link for all links used on the platform

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#239]
Since I started to collect political statements for dignitas.ro, I observed that many pages and links cited in news older than 2 years have disappeared. This is a known issue all over the world. 
In order to preserve the links used on dignitas _in the long run_ (statement sources, relation sources etc, links used in the answers etc), we could use a service similar to perma.cc. For example, Perma.cc is open source, [available on Github](https://github.com/harvard-lil/perma) and dual licensed under the MIT and GPL licenses.

**Comment by CatalinFrancu** [comment]
Some thoughts / a very crude design document. There are some decisions to be made, please feel free to contribute.

### perma.cc, self-hosted installation of Perma, or a different solution?

We will begin with option 1, while we don't have a lot of links to archive. But I will also tinker with option 3 below and report back.

#### 1. Notes about using perma.cc:

* It Just Works™.
* It is third party and very reputable, so it gives credibility to the page contents (now dead).
* **But** it costs 0.20-0.25 USD/link. We might qualify for free service, I will inquire, but don't have high hopes for it.

#### 2. Notes about using self-hosted Perma

* We have to get it to work. :-) The [installation instructions](https://github.com/harvard-lil/perma/blob/develop/install.md) are quite complex.

#### 3. Notes about using a different solution

- [ ] TODO: Set up https://archivebox.io/, see how easy it is.

### What links should we archive?

Here is an exhaustive list of fields that _are_ URLs or _can contain_ URLS:

* Link.url (web pages of authors, statement sources, relationship sources)
* Answer.contents
* CannedResponse.contents
* Comment.contents
* Entity.profile
* HelpPage.contents,
* Statement.context
* User.aboutMe

If we end up using Perma.cc commercially, we can cut back on the number of links. Examples:

* Only archive author / statement / relationship links one month after they were created. This gives the community time to flag and delete objects if necessary, so we don't archive spam.
* Only archive links in statements with verdicts and accepted answers.

### Backend design

We should archive URLs with a nightly script. Perma.cc has an API, so in theory the backend could parse and archive the links as soon as the page is saved. However, I can think of two reasons we should not do this synchronously:

* Accessing an external API can be slow (Perma.cc certainly feels sluggish).
* The external API could be unavailable (or our $$$ balance could be zero at the moment etc.).

The nightly script should collect all the objects that qualify (statement sources, accepted answers etc.) and extract all links. It should then archive said links. This can probably done in batch (a single call to the service).

There should be a separate table for archived URLs, matching real URLs to archived ones. We should not add new fields to existing tables and we should not inject new HTML into existing fields. In particular, we shouldn't alter user-submitted statements and answers to inject archive URLs.

### What should the UI look like?

It is easy to open a [Bootstrap popover](https://getbootstrap.com/docs/4.5/components/popovers/) whenever the user clicks a link for which we have an archived version. The popover could contain a link, _archived version_, perhaps with the Perma logo.

This can become annoying if the user is in the habit of clicking on these links often. However, there is no easy way to display the popover only when the link is dead. We would have to crawl the links periodically, and even that provides no guarantees (I have seen newspapers that redirect to the home page instead of returning a 404).

**Comment by CatalinFrancu** [comment]
Here is an update about ArchiveBox, the self-hosted archiving option.

I managed to set it up (the first 90% were really easy). Here are some URLS:

* backup of dexonline page: [link](https://dignitas.ro/archive/1614952592.079853/dexonline.ro/definitie/abstrus.html);
* single-page backup of dexonline page: [link](https://dignitas.ro/archive/1614952592.079853/singlefile.html);
* backup of Adevărul page: [link](https://dignitas.ro/archive/1614953339.260956/adevarul.ro/news/politica/clotilde-armand-s-a-facut-ras-acuzat-romania-pierdut-portal-12-milioane-euro-fapt-costa-12-euro-1_5e4510c05163ec42710cae91/index.html);
* single-page backup of Adevărul page: [link](https://dignitas.ro/archive/1614953339.260956/singlefile.html);
* backup of PDF: [link](https://dignitas.ro/archive/1614952901.853916/www.roaep.ro/legislatie/wp-content/uploads/2020/07/HG-calendar-alegeri-locale.pdf).

(FYI, a single-page backup puts everything in one single file, including the images. It loads faster, but it has a problem. In my experiments, whenever there were cookies to accept, the single-file version would not work.)

We can display these in an HTML frame and add the Dignitas header above.

ArchiveBox has its own header frame (see the [Screenshots section](https://github.com/ArchiveBox/ArchiveBox#screenshots), last screenshot), but it's not very pretty and not easy to customize.

All things considered, I changed my mind. :-) I would prefer to use ArchiveBox unless it is vital to use a third-party provider for credibility.

**Comment by CatalinFrancu** [comment]
@sandriu Here is a [UI suggestion](https://embed.plnkr.co/plunk/HLqrJ6). It is basically a tooltip that opens on hover and disappears when the user hovers away, **unless** the user hovers over the tooltip, in which case it stays open (and is clickable). For our needs, the tooltip could read "archived version".

This won't work on mobiles.

Assigning you until we figure out a good UI. :-)

**Comment by CatalinFrancu** [comment]
I implemented the delayed tooltip. Leftovers:

- [ ] Figure out a solution on mobile devices.
- [ ] Refetch failed jobs periodically.
- [ ] Archived PDF don't seem to render properly on mobiles.

**Comment by sandriu** [comment]
One of the limitations of designing for mobile is 'designing for interruptions' (because mobiles are portable), says [Nielsen Norman Group](https://www.nngroup.com/articles/mobile-ux/). "It also means prioritizing the essential and simplifying tasks and interactions because attention is fragmented" (same article).

So I believe it's ok _**not to display**_ the archived versions of links on mobile, because this feature is not essential on mobile. 
However, we should tell the users somehow that 'archived links' is a desktop-only feature, so they can check the desktop site for the full information.

**Comment by CatalinFrancu** [comment]
I don't have a solution for archiving Facebook pages that works consistently. I am giving up for now. Facebook should not be used as a means for publishing anything on the web.

**Comment by sandriu** [comment]
I have tested the archived version of a page on mobile portrait and it looks ok, except the scrolling area (the image) is small (about half of the screen). On mobile landscape, the scrolling area is even smaller (less than 50px height) so the image cannot be been at all - this must be fixed.

**Comment by CatalinFrancu** [comment]
I thought we weren't covering mobiles at all. :-) But if we are, then one approach would be to adjust the iframe size to fit its contents. This would need to be done using Javascript.

**Comment by sandriu** [comment]
> I thought we weren't covering mobiles at all. :-) But if we are, then one approach would be to adjust the iframe size to fit its contents. This would need to be done using Javascript.

@CatalinFrancu Can you adjust the iframe size, please? It's not urgent.

**Comment by CatalinFrancu** [comment]
It turns out [it's not trivial](https://stackoverflow.com/a/8223390/6022817) to adjust the iframe height automatically. We would have to modify the iframe contents (the archived page). Technically we could do that, but it would be messy.

As a workaround, I set the iframe height to 100vh, so the user can scroll it into view.

**Comment by CatalinFrancu** [comment]
I think we can close this. We still don't have a solution to the Facebook login wall, but we may never have one.
