### ISSUE TITLE
Bug: some tables do not have certain style components

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#300]
Some tables do not have the heading line:
- [x] invitations table: 
![dignitas-ss-bug-invitations-no-heading-line](https://user-images.githubusercontent.com/1265882/143209225-c3071f81-9d3a-4443-83cc-9b201cc84be1.png)

- [x] actions table: 
![dignitas-ss-actions-table-no-heading-line](https://user-images.githubusercontent.com/1265882/143209901-2615c871-429a-4c43-a18d-61d1e0411b0e.png)

And some tables do not have a heading text:
- [x] notifications table: 
![dignitas-ss-bug-notification-table-no-heading](https://user-images.githubusercontent.com/1265882/143221059-823e350d-ea69-48e2-8542-abe495a7b1db.png)

- [x] Some tables lacked the `mt-5` class after the gtable was implemented.

- [ ] grid tables are displayed strangely on mobile: all table headings are displayed on different rows (instead of one row); Bootstrap defines 'responsive tables' as 'tables that can be scrolled horizontally', see [here](https://getbootstrap.com/docs/4.0/content/tables/#responsive-tables).

**Comment by CatalinFrancu** [comment]
Done. Please take a look at the responsive wrapping on the notification page. I am not happy with it, but keeping on the information on one line also looks bad.

**Comment by sandriu** [comment]
On user profile page, the Actions table looks like this on mobiles:
![Screenshot_20211203-113854](https://user-images.githubusercontent.com/1265882/144581085-b66690c5-d3b8-4dd8-af50-467092185ecf.png)
![Screenshot_20211203-113908](https://user-images.githubusercontent.com/1265882/144581090-95053f41-54d1-4832-98d0-9a8e1da9ecdc.png)

This table does not wrap nicely on mobile, although the horizontal scrollbar (page bottom) is still there. Perhaps a Bootstrap class is missing?

**Comment by CatalinFrancu** [comment]
I think the culprit is further down, last one on the page:

![wrap](https://user-images.githubusercontent.com/1180392/144585655-b96ca170-8a7a-4206-8e34-24581ac7ba15.png)

It looks like URLs are normally wrapped nicely at `/` characters, but in this case there is one very long path component with no slashes. It looks like [this approach](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/) can fix it.

**Comment by CatalinFrancu** [comment]
Fixed! Please take another look.

**Comment by sandriu** [comment]
The URLs are normally wrapped now (on mobile), but the table headings are still displayed on 3 different rows (instead of having a horizontally scrollable table):
![Screenshot_20220117-153130](https://user-images.githubusercontent.com/1265882/149778917-decfe151-af28-4795-91d3-113904fa7614.png)

**Comment by CatalinFrancu** [comment]
The Bootstrap grid, by design, divides the screen into multiples of 1/12. It doesn't extend to fit contents (or at least I couldn't find a way). So I switched back to using responsive `<table>`s. The patch is now on staging and production.

Please take a look at these pages:

* user notifications;
* user actions ([example](https://dignitas.ro/utilizator/1/cata));
* object changes ([example](https://dignitas.ro/istoric-raspuns/100));
